# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52dc9a54d64337a918f4f51d39341ec479c3b352f93168d1ed8da7a170712097e15e37175b120dfb170506c819da248510252be80d64f45f180f016ccc89885b

test:
  secret_key_base: 5b025eb15558a90e872be010103861c0b532acef84a70c001d5bb36c98a0a621a623209bdb6281d386dc1849c140cd6dbff3d0aeffc76f3413e1ed82c3f8e767

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
